# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_nbdev',
                'doc_host': 'https://timsteeno.github.io',
                'git_url': 'https://github.com/timsteeno/test_nbdev',
                'lib_path': 'test_nbdev'},
  'syms': {'test_nbdev.core': {'test_nbdev.core.foo': ('core.html#foo', 'test_nbdev/core.py')}}}
